need to set up random non-cs non-cs-1 data first

In [8]:
import pandas as pd
import random

In [3]:
df = pd.read_csv('non_cs_sentences_full.csv')
df.head()

,Unnamed: 0,sent_type,university,sent_id,aligned_to,sentence,cs_word_id,preceding_zh,first_cs_word_zh,Unnamed: 9,...,cs_word_dep_dist,cs_word_pos_zh,cs_word_pos_eng,sentence_length_zh,dep_prob_eng,dep_prob_zh,ngram_surp_eng,ngram_surp_zh,dep_surp_eng,dep_surp_zh
0,1,non-code-switch,CMU,296,CMU_2,路上 一般 见到 都 是 学生 ， 很少 见到 游民 ， 公寓 对面 是 公园 和 一 个 ...,12,，,公寓,7.239988,...,1,NN,NN,26,-4.938384,-4.421023,4.377766,7.239988,4.938384,4.421023
1,3,non-code-switch,CMU,3006,CMU_4,房子 的 照片 在 附件 中 ， 还有 好多 照片 放 不 上来 啦 。,3,的,照片,6.609683,...,8,NN,NNS,15,-4.733248,-4.101531,4.397641,6.609683,4.733248,4.101531
2,5,non-code-switch,CMU,70,CMU_5,房子 共 有 三 个 厕所 。,1,<s>,房子,7.039197,...,2,NN,NNP,7,-5.233766,-4.259048,8.735376,7.039197,5.233766,4.259048
3,7,non-code-switch,CMU,6777,CMU_6,没有 找到 寄存 的 地方 。,5,的,地方,6.734926,...,3,NN,NN,6,-6.209946,-3.666723,6.257577,6.734926,6.209946,3.666723
4,9,non-code-switch,CMU,4373,CMU_9,全部 木头 地板 ， 干净 。,2,全部,木头,7.167052,...,1,NN,JJ,6,-3.333372,-5.403542,4.367158,7.167052,3.333372,5.403542

In [28]:
sentences = list(df['sentence'])
#sentences = [sentence.split() for sentence in sentences]

In [29]:
sentences[0]

'路上 一般 见到 都 是 学生 ， 很少 见到 游民 ， 公寓 对面 是 公园 和 一 个 艺术馆 ， 环境 很 好 很 安静 。'

In [30]:
sentences = [sentence.split() for sentence in sentences]

In [31]:
sentences[0]

['路上',
 '一般',
 '见到',
 '都',
 '是',
 '学生',
 '，',
 '很少',
 '见到',
 '游民',
 '，',
 '公寓',
 '对面',
 '是',
 '公园',
 '和',
 '一',
 '个',
 '艺术馆',
 '，',
 '环境',
 '很',
 '好',
 '很',
 '安静',
 '。']

In [32]:
cs_1_words = list(df['first_cs_word_zh'])

In [33]:
len(sentences) == len(cs_1_words)

True

In [34]:
without_cs1_sentences = []

for i in range(len(sentences)):
    sentence = sentences[i]
    word = cs_1_words[i]
    sentence.remove(word)
    without_cs1_sentences.append(sentence)

In [55]:
random_non_cs_words = []
for sentence in without_cs1_sentences:
    length = len(sentence)
    num = random.randint(0, length-1)
    word = sentence[num]
    random_non_cs_words.append(word)

In [56]:
len(random_non_cs_words)

1476

In [57]:
lengths = [len(word) for word in random_non_cs_words]

In [58]:
import spacy
from nltk import tokenize
nlp = spacy.load("zh_core_web_sm")

In [59]:
tags = []
for word in random_non_cs_words:
    doc = nlp(word)
    for token in doc:
        tags.append(token.tag_)
        break

In [74]:
import urllib
import requests

match_counts = []

for char in random_non_cs_words:
    if '~' in str(char) or '*' == str(char) or '?' == str(char):
        match_counts.append(1)
    else:
        encoded_query = urllib.parse.quote(str(char))
        params = {'corpus': 'chi', 'query': encoded_query, 'topk': 3}
        params = '&'.join('{}={}'.format(name, value) for name, value in params.items())

        response = requests.get('https://api.phrasefinder.io/search?' + params)

        assert response.status_code == 200

        try:
            match_counts.append(dict(response.json())['phrases'][0]['mc'])
        except:
            match_counts.append(1)

In [75]:
len(match_counts)

1476

In [76]:
match_counts

[1,
 3591356,
 158123333,
 1,
 47369,
 1,
 15319,
 1,
 3859805,
 62723,
 928104010,
 210714881,
 1,
 180808,
 32289774,
 210969,
 193088,
 6696896,
 931542,
 1,
 1344582,
 1,
 79710,
 1,
 248927028,
 1,
 10480067,
 13406620,
 32315960,
 1,
 66795262,
 1,
 9712177,
 193088,
 839611,
 528897,
 106070,
 1755695812,
 81985449,
 1,
 86430,
 85189509,
 132786553,
 210395,
 702967,
 1,
 3816,
 1,
 5695793,
 1,
 1,
 207535,
 220742,
 1,
 207535,
 32289774,
 180808,
 938121,
 7427435,
 2194025,
 1,
 1,
 1,
 63141564,
 574376,
 3657947,
 210714881,
 309573295,
 16292829,
 10480067,
 63141564,
 35727412,
 59920,
 158123333,
 1,
 4099,
 58260979,
 42262,
 1,
 1,
 1,
 702967,
 1755695812,
 1,
 96960,
 1,
 1,
 52120,
 1,
 832611,
 10480067,
 1,
 85189509,
 75260,
 1,
 1820337,
 44670074,
 1,
 1,
 261401,
 1,
 7403,
 250459,
 309573295,
 102491381,
 415409,
 890988,
 10480067,
 1,
 309573295,
 10031929,
 22307460,
 1,
 890988,
 44670074,
 6355830,
 529,
 2510218,
 594860,
 71491456,
 84719516,
 1,
 916502,
 14061883,
 63141564,
 26475062,
 17066463,
 32315960,
 1,
 71491456,
 25465651,
 6416190,
 39522387,
 365852,
 1240122,
 41958553,
 702967,
 1,
 44670074,
 253467,
 579212,
 66589060,
 1625207,
 27196509,
 132576,
 158123333,
 1,
 1,
 1846279,
 248927028,
 52120,
 1,
 1267,
 174888,
 1,
 1,
 5826939,
 396763,
 337367,
 1,
 1,
 1,
 11315932,
 1,
 5102,
 1,
 1,
 63288,
 85189509,
 28339549,
 702613,
 63141564,
 20339613,
 71491456,
 1,
 13243573,
 44408,
 199000,
 195091,
 132786553,
 1,
 23135859,
 420990,
 1,
 23625,
 1,
 332084,
 8077992,
 248927028,
 1,
 3017968,
 890988,
 1,
 1820337,
 19383165,
 210714881,
 6730260,
 18581067,
 1,
 594860,
 1,
 2906086,
 121881,
 1,
 1,
 1,
 1,
 1,
 11766985,
 250459,
 110826,
 1,
 63141564,
 1,
 12225,
 1,
 873,
 210714881,
 4130277,
 3040881,
 65682899,
 281099196,
 1,
 928104010,
 1,
 79894,
 31295152,
 1,
 210714881,
 13356,
 702967,
 16567719,
 667712,
 1,
 1,
 1,
 1,
 22307460,
 63141564,
 1,
 1,
 1468916,
 309573295,
 3017968,
 1,
 44670074,
 1,
 44670074,
 1755695812,
 32289774,
 44670074,
 19981133,
 248927028,
 1,
 11054,
 1,
 1,
 1,
 396763,
 210714881,
 3387,
 171804,
 1,
 180808,
 226,
 1,
 180808,
 25650328,
 86117888,
 1,
 210714881,
 1,
 1755695812,
 35727412,
 396763,
 1755695812,
 594860,
 210714881,
 27015914,
 195091,
 44670074,
 27314522,
 18285123,
 317717,
 86904,
 1,
 1255752,
 44670074,
 55317544,
 35289,
 1,
 1,
 1,
 1,
 10327932,
 281099196,
 1,
 1,
 21320673,
 1506956,
 1359442,
 9454218,
 207535,
 1,
 1276389,
 63141564,
 1,
 178919,
 1602,
 1,
 3016021,
 1625240,
 71491456,
 396763,
 32315960,
 2837805,
 66459765,
 468756,
 1,
 1,
 71491456,
 71491456,
 1181708,
 1625207,
 1,
 7690,
 1,
 7427435,
 1,
 13528147,
 1,
 1468916,
 965156,
 2936938,
 23874,
 72919,
 1,
 6913533,
 262515,
 53986122,
 44670074,
 1483025,
 250459,
 49021,
 250459,
 1,
 71491456,
 19904,
 1103861,
 16281323,
 206,
 1,
 1519,
 66459765,
 250459,
 120203,
 210714881,
 15640156,
 7427435,
 345576,
 1755695812,
 1,
 62723,
 71491456,
 32315960,
 210714881,
 6072970,
 118180,
 55317544,
 44670074,
 25381169,
 58260979,
 178919,
 9454218,
 1,
 1,
 210714881,
 1,
 1755695812,
 17250,
 12792001,
 1,
 210714881,
 1,
 3630016,
 210714881,
 420990,
 5653583,
 171804,
 7423087,
 193088,
 57047001,
 9454218,
 5419127,
 1,
 253467,
 1,
 27196509,
 1,
 895,
 430785,
 1,
 4378675,
 594860,
 1,
 55317544,
 1702508,
 80877,
 32289774,
 305838,
 126286286,
 44670074,
 158123333,
 210714881,
 12861295,
 1,
 1,
 14869633,
 41305469,
 157587,
 52120,
 1755695812,
 17591926,
 32315960,
 309573295,
 140639,
 210714881,
 210714881,
 1,
 71491456,
 9454218,
 1,
 3016021,
 180808,
 2091,
 158123333,
 14286316,
 22307460,
 702967,
 1,
 35727412,
 244565,
 2278997,
 1607,
 20614,
 772240,
 431590,
 1,
 1755695812,
 281099196,
 35727412,
 248927028,
 253806,
 1,
 594860,
 1813639,
 2754331,
 6730260,
 29699,
 55317544,
 23816,
 2627578,
 768103,
 158123333,
 32289774,
 1,
 1,
 1,
 7586937,
 1,
 1,
 3024075,
 1755695812,
 248927028,
 837441,
 37344568,
 71491456,
 210714881,
 35727412,
 31481,
 391209,
 4703279,
 1267,
 1368652,
 7325490,
 8586717,
 1,
 13406620,
 1,
 928104010,
 1,
 1755695812,
 1,
 156162569,
 248927028,
 281099196,
 1,
 4682752,
 1,
 2224915,
 79098,
 32289774,
 4117,
 36145183,
 1,
 16066077,
 981050,
 41516,
 158123333,
 3017968,
 12225,
 443,
 694630,
 12557305,
 1625207,
 63288,
 71491456,
 1,
 35727412,
 928104010,
 107970419,
 102588945,
 32679356,
 5826939,
 1,
 34995,
 6543116,
 44670074,
 191332,
 18248093,
 58260979,
 1,
 248927028,
 1872370,
 1,
 3587,
 725361,
 1,
 420990,
 894,
 26477,
 1,
 94947,
 1,
 1,
 1,
 258853,
 9454218,
 23625,
 1,
 248927028,
 1366355,
 23625,
 27015914,
 1707580,
 5653583,
 261,
 1755695812,
 66589060,
 1,
 12822985,
 16567719,
 5573673,
 1755695812,
 138212,
 1,
 32289774,
 171804,
 309573295,
 1,
 195091,
 120600,
 57047001,
 636628,
 1,
 126286286,
 309573295,
 2854440,
 22836851,
 44670074,
 1,
 1,
 14647386,
 1,
 4164211,
 1,
 1625207,
 1,
 10572258,
 6072970,
 1,
 1,
 132786553,
 79241,
 3017968,
 174936,
 2978349,
 3017968,
 19409757,
 6030398,
 82608,
 11015328,
 468756,
 1,
 32289774,
 1,
 1209012,
 420990,
 193088,
 16773359,
 639085,
 10717,
 185781,
 1121348,
 26727,
 309573295,
 12822985,
 158123333,
 2978349,
 1,
 27015914,
 1,
 16488155,
 1755695812,
 4130277,
 1843884,
 15768676,
 573024,
 890988,
 9454218,
 1669,
 132786553,
 3133381,
 890988,
 42721,
 1,
 210714881,
 1,
 132786553,
 309573295,
 105444,
 85892,
 1846279,
 158123333,
 97864,
 253467,
 792,
 6975964,
 1,
 792,
 28372,
 179965,
 86117888,
 132786553,
 3017968,
 57047001,
 22571,
 5826939,
 928104010,
 4538968,
 309573295,
 890988,
 984795,
 1,
 1,
 1,
 5826939,
 1,
 1755695812,
 323993,
 9866832,
 1,
 281099196,
 150596,
 28339549,
 4018,
 3462542,
 158123333,
 1,
 1,
 71491456,
 25465651,
 4214843,
 1,
 1,
 12116907,
 3089504,
 20339613,
 38102290,
 1,
 1,
 32289774,
 7800151,
 210461,
 1,
 1,
 14646255,
 1355061,
 1,
 44670074,
 1,
 26481627,
 953710,
 2837805,
 1949899,
 4130277,
 6730260,
 1,
 3016021,
 1755695812,
 652775,
 235983,
 3017968,
 11630360,
 792,
 3763521,
 1001630,
 174888,
 4252489,
 210714881,
 309573295,
 2478229,
 71491456,
 1,
 177761,
 3869,
 594860,
 6536145,
 1755695812,
 180808,
 9771843,
 20339613,
 2278240,
 171142,
 253806,
 58356,
 309573295,
 27240151,
 1755695812,
 1,
 1,
 1,
 13675,
 210714881,
 1,
 34414173,
 245111,
 174888,
 44444556,
 1,
 42427,
 23261,
 28716,
 1135775,
 1142705,
 12116907,
 1,
 6030398,
 1,
 2417127,
 15504,
 9502161,
 294054706,
 27240151,
 248927028,
 318779,
 1,
 5728680,
 792,
 195091,
 272555,
 1321421,
 9866832,
 9418412,
 1,
 1,
 361936,
 10480067,
 1,
 85189509,
 2742883,
 1,
 1,
 25465651,
 56650,
 1,
 1,
 1,
 173395,
 19981133,
 5327,
 1079455,
 85189509,
 158123333,
 748617,
 752,
 748617,
 1755695812,
 1,
 1,
 67438369,
 13584604,
 3016021,
 1,
 9454218,
 1,
 1,
 3598953,
 1,
 4742,
 2881129,
 1,
 1,
 101887,
 20339613,
 928104010,
 1,
 2297,
 245111,
 1,
 52120,
 50671348,
 91012,
 71491456,
 1755695812,
 10480067,
 16567719,
 17817,
 1,
 3439925,
 6030398,
 32289774,
 305894,
 300781,
 6597,
 44670074,
 16369403,
 250459,
 491294,
 410082,
 57047001,
 271256,
 71491456,
 294054706,
 20227283,
 20339613,
 1755695812,
 1,
 210292,
 55697,
 120600,
 1,
 34330,
 14941872,
 6416190,
 14646255,
 1,
 5843,
 654,
 12225,
 6730260,
 18248093,
 497938,
 1771701,
 3417416,
 2920857,
 19409757,
 45445,
 52120,
 1,
 1,
 58356,
 1,
 52228117,
 639085,
 1946073,
 102588945,
 34118,
 158123333,
 1,
 41274617,
 1,
 11398783,
 178357,
 3462542,
 35577298,
 85189509,
 1,
 87186,
 511804,
 1,
 14685569,
 116152,
 1,
 1,
 271893,
 9167726,
 66589060,
 1,
 2170430,
 1,
 737567,
 1,
 63141564,
 792,
 1129039,
 1,
 4791017,
 1344582,
 106815,
 27314522,
 4989901,
 3724,
 29320801,
 8586717,
 1,
 1,
 12822985,
 16567719,
 41490,
 2596525,
 570373,
 15264872,
 6730260,
 21232991,
 286,
 253467,
 79098,
 245111,
 18679385,
 1,
 20339613,
 12570722,
 63288,
 85189509,
 55317544,
 1,
 702967,
 6326629,
 27015914,
 6730260,
 1,
 294054706,
 1,
 1,
 309573295,
 6030398,
 48190,
 1,
 7958072,
 23135859,
 1,
 6146572,
 1,
 49571199,
 1038488,
 22307460,
 479155,
 8481641,
 594860,
 1,
 1,
 281099196,
 396763,
 71491456,
 27314522,
 39522387,
 1,
 180864,
 25465651,
 1,
 34414173,
 1,
 7958072,
 148037,
 44444556,
 1755695812,
 1,
 158123333,
 27015914,
 748617,
 158123333,
 992656,
 13406620,
 55317544,
 792,
 44408,
 1,
 48455208,
 31162,
 5826939,
 396763,
 309573295,
 1,
 262515,
 3017968,
 1,
 1,
 309573295,
 2006003,
 ...]

In [77]:
import numpy as np
frequencies = [-np.log(num/26859461025) for num in match_counts]

In [85]:
file = open('final_non_cs_zh_ngram_output.txt', 'r')
lines = []
for line in file.readlines(): 
    lines.append(line[:-1].split())

In [88]:
lines = lines[:1476]

In [89]:
lines[-1]

['<s>=1',
 '1',
 '-0.18438905',
 '房型=0',
 '1',
 '-7.3514414',
 '是=28984',
 '1',
 '-4.2973504',
 '两=0',
 '1',
 '-7.39772',
 '室=6109055',
 '1',
 '-7.1598167',
 '一=61189',
 '1',
 '-5.594116',
 '厅=0',
 '1',
 '-7.2162104',
 '一=61189',
 '1',
 '-5.580385',
 '厨=0',
 '1',
 '-7.2162104',
 '一=61189',
 '1',
 '-5.580385',
 '卫=0',
 '1',
 '-7.2162104',
 '，=16717',
 '1',
 '-4.1666403',
 '客厅=0',
 '1',
 '-7.239988',
 '空间=649008',
 '1',
 '-6.558925',
 '大=128062',
 '1',
 '-6.132743',
 '，=16717',
 '1',
 '-4.1803713',
 '采光=0',
 '1',
 '-7.239988',
 '良好=0',
 '1',
 '-7.1670523',
 '，=16717',
 '1',
 '-4.1666403',
 '冬=1428934',
 '1',
 '-6.534768',
 '有=205088',
 '1',
 '-5.239348',
 '暖气=0',
 '1',
 '-7.2971773',
 '夏=1636027',
 '1',
 '-6.1604376',
 '有=205088',
 '1',
 '-5.239348',
 '空调=0',
 '1',
 '-7.2971773',
 '。=74',
 '1',
 '-3.0130775',
 '</s>=2',
 '2',
 '-0.027683549',
 'Total:',
 '-152.4556',
 'OOV:',
 '10']

In [90]:
new_lines = []
for line in lines:
    new_line = []
    for char in line:
        if '=' in char:
            equal_index = char.index('=')
            word = char[:equal_index]
            #s = ''.join(ch for ch in word if ch.isalnum())
            new_line.append(word)
        else:
            new_line.append(char)
    new_lines.append(new_line)

In [91]:
new_lines[0]

['<s>',
 '1',
 '-0.18438905',
 '路上',
 '1',
 '-7.3514414',
 '一般',
 '1',
 '-7.1598167',
 '见到',
 '1',
 '-7.1807833',
 '都',
 '1',
 '-7.1670523',
 '是',
 '1',
 '-4.2973504',
 '学生',
 '1',
 '-7.3904843',
 '，',
 '1',
 '-4.1803713',
 '很少',
 '1',
 '-7.239988',
 '见到',
 '1',
 '-7.1670523',
 '游民',
 '1',
 '-7.1670523',
 '，',
 '1',
 '-4.1666403',
 '公寓',
 '1',
 '-7.239988',
 '对面',
 '1',
 '-7.1670523',
 '是',
 '1',
 '-4.2973504',
 '公园',
 '1',
 '-7.3904843',
 '和',
 '1',
 '-3.4306083',
 '一',
 '1',
 '-5.662717',
 '个',
 '1',
 '-5.762203',
 '艺术馆',
 '1',
 '-7.1875896',
 '，',
 '1',
 '-4.1666403',
 '环境',
 '1',
 '-7.2327523',
 '很',
 '1',
 '-7.1807833',
 '好',
 '1',
 '-6.558925',
 '很',
 '1',
 '-7.1807833',
 '安静',
 '1',
 '-7.1670523',
 '。',
 '1',
 '-3.0130775',
 '</s>',
 '2',
 '-0.027683549',
 'Total:',
 '-161.31813',
 'OOV:',
 '12']

In [93]:
surps = []
for i in range(len(new_lines)):
    line = new_lines[i]
    word = random_non_cs_words[i]
    try:
        index = line.index(word)
        surps.append(-float(line[index+2]))
    except:
        surps.append('TODO')

In [94]:
surps.count('TODO')

1

In [95]:
surps.index('TODO')

475

In [97]:
random_non_cs_words[475]

'1'

In [98]:
new_lines[475]

['<s>',
 '1',
 '-0.18438905',
 '我们',
 '1',
 '-7.3514414',
 '的',
 '1',
 '-4.1759996',
 '需求',
 '1',
 '-7.21781',
 '：',
 '1',
 '-4.4276857',
 '1',
 '1',
 '-4.6128607',
 '.',
 '2',
 '-4.356689',
 '</s>',
 '2',
 '-0.29684272',
 'Total:',
 '-32.623722',
 'OOV:',
 '2']

In [99]:
surps[475] = 4.6128607

In [100]:
len(random_non_cs_words) == len(tags) == len(frequencies) == len(lengths) == len(surps)

True

In [101]:
sentence_length = list(df['sentence_length_zh'])

In [102]:
all_rows = []
for i in range(len(surps)):
    row = []
    row.append(random_non_cs_words[i])
    row.append(frequencies[i])
    row.append(tags[i])
    row.append(lengths[i])
    row.append(sentence_length[i])
    row.append(surps[i])
    all_rows.append(row)

In [103]:
non_cs_data = pd.DataFrame (all_rows, columns = ['random_non_cs_1_word','word_freq_zh', 'cs_word_pos_zh', 'cs_word_length_zh', 'sentence_length_zh', 'ngram_surp_zh'])

In [104]:
non_cs_data.head()

,random_non_cs_1_word,word_freq_zh,cs_word_pos_zh,cs_word_length_zh,sentence_length_zh,ngram_surp_zh
0,。,24.013884,PU,1,26,3.013078
1,放,8.919844,VV,1,15,7.446082
2,有,5.134998,VE,1,7,5.239348
3,。,24.013884,PU,1,6,3.108282
4,地板,13.248161,NN,2,6,7.167052

In [105]:
non_cs_data.to_csv('random_non_cs_1_data.csv')

In [106]:
non_cs_data = non_cs_data[['word_freq_zh', 'cs_word_pos_zh', 'cs_word_length_zh',
       'sentence_length_zh', 'ngram_surp_zh']]

In [119]:
non_cs_data.head()

,word_freq_zh,cs_word_pos_zh,cs_word_length_zh,sentence_length_zh,ngram_surp_zh,code_switched
0,24.013884,PU,1,26,3.013078,0
1,8.919844,VV,1,15,7.446082,0
2,5.134998,VE,1,7,5.239348,0
3,24.013884,PU,1,6,3.108282,0
4,13.248161,NN,2,6,7.167052,0

In [107]:
cs_data = df[['word_freq_zh', 'cs_word_pos_zh', 'cs_word_length_zh',
       'sentence_length_zh', 'ngram_surp_zh']]

In [118]:
cs_data.head()

,word_freq_zh,cs_word_pos_zh,cs_word_length_zh,sentence_length_zh,ngram_surp_zh,code_switched
0,39.049880,NN,2,26,7.239988,1
1,37.173947,NN,2,15,6.609683,1
2,37.403903,NN,2,7,7.039197,1
3,34.498460,NN,2,6,6.734926,1
4,40.617086,NN,2,6,7.167052,1

In [108]:
len(cs_data) == len(non_cs_data)

True

In [109]:
code_switched = [1]* len(cs_data)
cs_data['code_switched'] = code_switched
non_code_switched = [0] * len(non_cs_data)
non_cs_data['code_switched'] = non_code_switched

/Users/Debasmita/Library/Python/3.7/lib/python/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [110]:
frames = [cs_data, non_cs_data]
all_data = pd.concat(frames)

In [111]:
all_data.head()

,word_freq_zh,cs_word_pos_zh,cs_word_length_zh,sentence_length_zh,ngram_surp_zh,code_switched
0,39.049880,NN,2,26,7.239988,1
1,37.173947,NN,2,15,6.609683,1
2,37.403903,NN,2,7,7.039197,1
3,34.498460,NN,2,6,6.734926,1
4,40.617086,NN,2,6,7.167052,1

In [112]:
all_data.tail()

,word_freq_zh,cs_word_pos_zh,cs_word_length_zh,sentence_length_zh,ngram_surp_zh,code_switched
1471,11.427497,NN,2,14,7.159817,0
1472,17.339323,NR,2,6,7.239988,0
1473,12.226757,NN,2,6,7.351441,0
1474,6.742236,NN,2,5,5.956181,0
1475,12.531830,NN,2,25,7.239988,0

In [113]:
len(all_data)

2952

In [114]:
as_ints = []
for pos in all_data['cs_word_pos_zh']:
    if pos == 'NN':
        as_ints.append(0)
    elif pos == 'NR':
        as_ints.append(0)
    elif pos == 'NT':
        as_ints.append(0)
    elif pos == 'VE':
        as_ints.append(1)
    elif pos == 'VV':
        as_ints.append(1)
    else:
        as_ints.append(2)

In [115]:
ngram_surp = all_data[['word_freq_zh', 'cs_word_pos_zh', 'cs_word_length_zh',
       'sentence_length_zh', 'ngram_surp_zh', 'code_switched']]
ngram_surp['cs_word_pos_zh'] = as_ints

In [116]:
ngram_surp_final = ngram_surp[['word_freq_zh', 'cs_word_pos_zh', 'cs_word_length_zh', 'sentence_length_zh', 'ngram_surp_zh' ]]

In [117]:
ngram_surp_final.head()

,word_freq_zh,cs_word_pos_zh,cs_word_length_zh,sentence_length_zh,ngram_surp_zh
0,39.049880,0,2,26,7.239988
1,37.173947,0,2,15,6.609683
2,37.403903,0,2,7,7.039197
3,34.498460,0,2,6,6.734926
4,40.617086,0,2,6,7.167052

In [120]:
cs_word_frequency = np.array(ngram_surp_final['word_freq_zh'])
cs_word_length = np.array(ngram_surp_final['cs_word_length_zh'])
sentence_length = np.array(ngram_surp_final['sentence_length_zh'])
ngram_surp_val = np.array(ngram_surp_final['ngram_surp_zh'])

cs_word_frequency_new = (cs_word_frequency-np.mean(cs_word_frequency))*0.5/np.std(cs_word_frequency)
cs_word_length_new = (cs_word_length-np.mean(cs_word_length))*0.5/np.std(cs_word_length)
sentence_length_new = (sentence_length-np.mean(sentence_length))*0.5/np.std(sentence_length)
ngram_surp_new = (ngram_surp_val-np.mean(ngram_surp_val))*0.5/np.std(ngram_surp_val)

ngram_surp_final['word_freq_zh'] = cs_word_frequency_new
ngram_surp_final['cs_word_length_zh'] = cs_word_length_new
ngram_surp_final['sentence_length_zh'] = sentence_length_new
ngram_surp_final['ngram_surp_zh'] = ngram_surp_new

/Users/Debasmita/Library/Python/3.7/lib/python/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
/Users/Debasmita/Library/Python/3.7/lib/python/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/Users/Debasmita/Library/Python/3.7/lib/python/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
/Users/Debasmita/Library/Python/3.7/lib/python/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [121]:
ngram_surp_final.head()

,word_freq_zh,cs_word_pos_zh,cs_word_length_zh,sentence_length_zh,ngram_surp_zh
0,0.514756,0,0.175694,1.446090,0.297716
1,0.445511,0,0.175694,0.430706,0.045801
2,0.453999,0,0.175694,-0.307755,0.217466
3,0.346753,0,0.175694,-0.400062,0.095858
4,0.572605,0,0.175694,-0.400062,0.268566

In [123]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, mean_squared_error
from sklearn.model_selection import cross_validate

import statsmodels.api as sm 
import statsmodels.formula.api as smf

import math

In [124]:
X = ngram_surp_final
y = ngram_surp['code_switched']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [125]:
clf = LogisticRegression()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

In [126]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       419
           1       1.00      1.00      1.00       467

    accuracy                           1.00       886
   macro avg       1.00      1.00      1.00       886
weighted avg       1.00      1.00      1.00       886

In [127]:
print(clf.coef_)
print(clf.intercept_)

[[10.48309219 -0.63003225 -1.69262597  0.11937688  2.0421442 ]]
[0.20698742]

In [128]:
ngram_surp_final_new = X.copy()
ngram_surp_final_new['code_switched'] = y.copy()

In [129]:
model = smf.ols(formula="code_switched ~ word_freq_zh + C(cs_word_pos_zh) + cs_word_length_zh + sentence_length_zh + ngram_surp_zh",data=ngram_surp_final_new).fit() 
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:          code_switched   R-squared:                       0.878
Model:                            OLS   Adj. R-squared:                  0.878
Method:                 Least Squares   F-statistic:                     3537.
Date:                Sat, 14 May 2022   Prob (F-statistic):               0.00
Time:                        22:40:35   Log-Likelihood:                 964.15
No. Observations:                2952   AIC:                            -1914.
Df Residuals:                    2945   BIC:                            -1872.
Df Model:                           6
Covariance Type:            nonrobust
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                  0.4932      0.005     93.763      0.000       0.483       0.504
C(cs_word_pos_zh)[T.1]     0.0307      0.010      3.227      0.001       0.012       0.049
C(cs_word_pos_zh)[T.2]     0.0043      0.009      0.499      0.618      -0.013       0.021
word_freq_zh               0.8838      0.007    129.151      0.000       0.870       0.897
cs_word_length_zh         -0.1016      0.007    -14.583      0.000      -0.115      -0.088
sentence_length_zh         0.0141      0.006      2.179      0.029       0.001       0.027
ngram_surp_zh              0.2166      0.008     27.495      0.000       0.201       0.232
==============================================================================
Omnibus:                       35.380   Durbin-Watson:                   1.738
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               61.002
Skew:                           0.005   Prob(JB):                     5.67e-14
Kurtosis:                       3.704   Cond. No.                         4.09
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""