In [54]:
import pandas as pd
import numpy as np
df = pd.read_csv('redoing_cs_data.csv')

In [55]:
df.head()

,sent_type,university,sent_id,aligned_to,original_sentence,eng_translation,zh_translation,cs_word_id,first_cs_word_form,first_cs_word_translation,...,surprisal_values,average_surprisal,bilingual_corpus_frequency_negative_log_first_cs_word,bilingual_corpus_frequency_negative_log_first_cs_word_trans,length_first_cs_word_form,dependency_distance,if_it_is_root,if_previous_word_is_punctuation,surprisal_of_previous_word,surprisal_first_cs_word_trans
0,code-switch,CMU,2,CMU_296,rich neighborhood ， 非常 安全 （ 这里 属于 富人 区 ） ， 旁边 ...,Rich neighborhood is very safe (it belongs to ...,富人 区 ， 非常 安全 （ 这里 属于 富人 区 ） ， 旁边 就 是 公园 ， 附近 还...,1,rich,富人,...,6.100998 1.320391 0.7630151 4.4722 3.20577 2.7...,3.144718,11.319098,10.402807,4,1,0,NaN,NaN,6.100998
1,code-switch,CMU,4,CMU_3006,lease 从 八月 开始 ， 具体 日期 可以 商量 。,Lease will begin in August and the date is neg...,租约 从 八月 开始 ， 具体 日期 可以 商量 。,1,lease,租约,...,6.527233 3.646975 4.193077 1.173965 0.5694761 ...,3.155464,7.348806,10.066335,5,8,0,NaN,NaN,6.527233
2,code-switch,CMU,5,CMU_70,house 一共 有 两 层 + 地下室 。,House has two floors plus basement.,房子 一共 有 两 层 + 地下室 。,1,house,房子,...,5.512905 5.228868 0.5955775 1.38895 2.136289 4...,3.268832,6.694125,7.084991,5,2,0,NaN,NaN,5.512905
3,code-switch,CMU,6,CMU_6777,一共 有 两 个 可以 洗澡 的 bathroom 。,There are two bathrooms for bathing.,一共 有 两 个 可以 洗澡 的 浴室 。,8,bathroom,浴室,...,4.509301 0.2903937 1.38895 0.4321387 3.465795 ...,2.642274,8.611048,9.709660,8,6,0,0.0,0.895995,5.210801
4,code-switch,CMU,9,CMU_4373,整个 house 家具 齐全 。,The whole house is fully furnished.,整个 房子 家具 齐全 。,2,house,房子,...,3.732348 4.488641 5.760885 6.166569 0.8237057,4.194430,6.694125,7.084991,5,1,0,0.0,3.732348,4.488641

In [56]:
df.columns

Index(['sent_type', 'university', 'sent_id', 'aligned_to', 'original_sentence',
       'eng_translation', 'zh_translation', 'cs_word_id', 'first_cs_word_form',
       'first_cs_word_translation', 'preceding_word',
       'preceding_word_translation', 'ngram_eng', 'ngram_zh', 'dep_eng',
       'dep_zh ', 'word_freq_zh', 'non_log_word_freq_zh',
       'neg_base_e_word_freq_zh', 'base_e_word_freq_zh', 'word_freq_eng',
       'non_log_word_freq_eng', 'neg_base_e_word_freq_eng',
       'base_e_word_freq_eng', 'cs_word_pos_zh', 'cs_word_pos_eng',
       'cs_word_length_zh', 'cs_word_length_eng', 'sentence_length_zh',
       'ngram_surp_zh', 'base_2_ngram_prob_zh', 'raw_ngram_prob_zh',
       'base_10_ngram_prob_zh', 'base_10_ngram_surp_zh',
       'retrained_ngram_surp_zh', 'dep_surp_zh', 'gt_ngram_surp_eng',
       'ngram_surp_eng', 'base_2_ngram_prob_eng', 'raw_ngram_prob_eng',
       'base_10_ngram_prob_eng', 'base_10_ngram_surp_eng', 'dep_surp_eng',
       'zh_word_index', 'cs_back_word', 'Unnamed: 45',
       'governor_first_cs_word_trans', 'deprel_first_cs_word_trans',
       'surprisal_values', 'average_surprisal',
       'bilingual_corpus_frequency_negative_log_first_cs_word',
       'bilingual_corpus_frequency_negative_log_first_cs_word_trans',
       'length_first_cs_word_form', 'dependency_distance', 'if_it_is_root',
       'if_previous_word_is_punctuation', 'surprisal_of_previous_word',
       'surprisal_first_cs_word_trans'],
      dtype='object')

In [57]:
with open('cs2_indices.txt') as f:
    cs2_lines = f.readlines()

In [58]:
cs2_lines = [item[:-1] for item in cs2_lines]
cs2_lines

['3',
 '1',
 '1',
 '2',
 '5',
 '4',
 '8',
 '12',
 '6',
 '5',
 '10',
 '9',
 '9',
 '6',
 '2',
 '3',
 '5',
 '4',
 '2',
 '2',
 '1',
 '4',
 '11',
 '11',
 '4',
 '11',
 '2',
 '7',
 '9',
 '5',
 '1',
 '6',
 '7',
 '2',
 '8',
 '11',
 '2',
 '10',
 '3',
 '14',
 '5',
 '5',
 '1',
 '3',
 '3',
 '6',
 '10',
 '4',
 '2',
 '3',
 '2',
 '1',
 '3',
 '11',
 '2',
 '12',
 '0',
 '8',
 '3',
 '3',
 '5',
 '5',
 '5',
 '1',
 '3',
 '2',
 '2',
 '14',
 '5',
 '4',
 '1',
 '7',
 '3',
 '6',
 '6',
 '4',
 '6',
 '1',
 '10',
 '12',
 '5',
 '3',
 '12',
 '2',
 '13',
 '2',
 '12',
 '3',
 '6',
 '5',
 '10',
 '1',
 '1',
 '5',
 '5',
 '19',
 '12',
 '5',
 '6',
 '1',
 '6',
 '6',
 '3',
 '3',
 '2',
 '0',
 '5',
 '2',
 '7',
 '2',
 '8',
 '5',
 '2',
 '6',
 '1',
 '1',
 '5',
 '14',
 '3',
 '3',
 '4',
 '16',
 '1',
 '22',
 '2',
 '2',
 '1',
 '4',
 '2',
 '4',
 '5',
 '1',
 '8',
 '14',
 '11',
 '20',
 '1',
 '7',
 '6',
 '4',
 '12',
 '14',
 '16',
 '4',
 '1',
 '4',
 '4',
 '16',
 '5',
 '4',
 '3',
 '20',
 '5',
 '10',
 '1',
 '4',
 '15',
 '4',
 '7',
 '5',
 '2',
 '5',
 '2',
 '6',
 '20',
 '2',
 '18',
 '10',
 '5',
 '9',
 '2',
 '4',
 '1',
 '12',
 '2',
 '10',
 '4',
 '4',
 '4',
 '7',
 '1',
 '10',
 '3',
 '1',
 '16',
 '11',
 '5',
 '2',
 '4',
 '2',
 '19',
 '6',
 '2',
 '3',
 '10',
 '4',
 '4',
 '7',
 '9',
 '4',
 '18',
 '1',
 '3',
 '9',
 '18',
 '5',
 '3',
 '0',
 '8',
 '5',
 '4',
 '6',
 '1',
 '3',
 '5',
 '6',
 '3',
 '7',
 '7',
 '10',
 '4',
 '2',
 '1',
 '13',
 '9',
 '1',
 '4',
 '8',
 '13',
 '1',
 '1',
 '1',
 '4',
 '6',
 '2',
 '1',
 '9',
 '4',
 '14',
 '5',
 '4',
 '2',
 '7',
 '2',
 '9',
 '3',
 '2',
 '2',
 '0',
 '6',
 '1',
 '4',
 '1',
 '4',
 '7',
 '7',
 '3',
 '2',
 '2',
 '16',
 '6',
 '3',
 '1',
 '6',
 '11',
 '5',
 '2',
 '1',
 '7',
 '2',
 '5',
 '5',
 '3',
 '4',
 '1',
 '4',
 '8',
 '7',
 '1',
 '17',
 '6',
 '2',
 '19',
 '12',
 '13',
 '3',
 '15',
 '13',
 '1',
 '3',
 '25',
 '1',
 '2',
 '1',
 '5',
 '1',
 '5',
 '1',
 '9',
 '8',
 '1',
 '2',
 '1',
 '1',
 '1',
 '4',
 '5',
 '3',
 '3',
 '5',
 '7',
 '1',
 '16',
 '2',
 '1',
 '5',
 '6',
 '5',
 '7',
 '10',
 '13',
 '2',
 '3',
 '2',
 '3',
 '7',
 '11',
 '4',
 '8',
 '3',
 '5',
 '6',
 '8',
 '8',
 '6',
 '2',
 '1',
 '12',
 '8',
 '2',
 '8',
 '4',
 '14',
 '3',
 '6',
 '7',
 '6',
 '26',
 '1',
 '4',
 '6',
 '13',
 '3',
 '2',
 '5',
 '2',
 '6',
 '7',
 '16',
 '24',
 '5',
 '17',
 '1',
 '7',
 '4',
 '0',
 '4',
 '7',
 '6',
 '6',
 '4',
 '4',
 '3',
 '3',
 '15',
 '8',
 '5',
 '6',
 '2',
 '7',
 '3',
 '13',
 '4',
 '2',
 '2',
 '0',
 '5',
 '7',
 '4',
 '7',
 '4',
 '15',
 '1',
 '6',
 '5',
 '3',
 '5',
 '7',
 '2',
 '15',
 '3',
 '6',
 '1',
 '2',
 '4',
 '4',
 '1',
 '4',
 '8',
 '1',
 '0',
 '5',
 '7',
 '2',
 '4',
 '11',
 '4',
 '6',
 '4',
 '6',
 '5',
 '4',
 '8',
 '5',
 '4',
 '2',
 '4',
 '3',
 '10',
 '16',
 '5',
 '6',
 '8',
 '9',
 '6',
 '13',
 '2',
 '2',
 '2',
 '4',
 '9',
 '2',
 '7',
 '5',
 '5',
 '9',
 '15',
 '18',
 '5',
 '5',
 '5',
 '6',
 '14',
 '3',
 '5',
 '9',
 '6',
 '5',
 '3',
 '5',
 '2',
 '4',
 '1',
 '8',
 '5',
 '4',
 '7',
 '6',
 '6',
 '7',
 '4',
 '5',
 '2',
 '6',
 '10',
 '4',
 '3',
 '23',
 '6',
 '7',
 '15',
 '11',
 '7',
 '2',
 '8',
 '3',
 '4',
 '3',
 '4',
 '2',
 '10',
 '2',
 '1',
 '6',
 '2',
 '5',
 '4',
 '9',
 '1',
 '3',
 '4',
 '12',
 '6',
 '10',
 '8',
 '10',
 '3',
 '7',
 '4',
 '3',
 '11',
 '3',
 '2',
 '4',
 '4',
 '3',
 '0',
 '8',
 '7',
 '9',
 '6',
 '6',
 '4',
 '2',
 '2',
 '3',
 '4',
 '14',
 '7',
 '2',
 '4',
 '3',
 '4',
 '2',
 '6',
 '9',
 '4',
 '3',
 '5',
 '3',
 '7',
 '15',
 '7',
 '2',
 '1',
 '2',
 '13',
 '1',
 '2',
 '14',
 '2',
 '8',
 '1',
 '14',
 '4',
 '4',
 '12',
 '2',
 '5',
 '3',
 '13',
 '6',
 '6',
 '20',
 '5',
 '6',
 '5',
 '2',
 '3',
 '6',
 '2',
 '1',
 '9',
 '1',
 '8',
 '2',
 '11',
 '6',
 '1',
 '5',
 '15',
 '2',
 '16',
 '4',
 '0',
 '6',
 '4',
 '7',
 '3',
 '1',
 '2',
 '2',
 '3',
 '7',
 '8',
 '2',
 '4',
 '3',
 '3',
 '3',
 '4',
 '4',
 '3',
 '2',
 '19',
 '7',
 '3',
 '9',
 '5',
 '2',
 '6',
 '7',
 '9',
 '11',
 '4',
 '2',
 '6',
 '3',
 '4',
 '2',
 '18',
 '7',
 '10',
 '3',
 '4',
 '8',
 '0',
 '10',
 '2',
 '3',
 '6',
 '2',
 '3',
 '11',
 '10',
 '1',
 '1',
 '2',
 '5',
 '6',
 '2',
 '4',
 '8',
 '15',
 '9',
 '7',
 '2',
 '6',
 '16',
 '2',
 '1',
 '16',
 '9',
 '2',
 '10',
 '1',
 '7',
 '5',
 '6',
 '3',
 '2',
 '6',
 '8',
 '2',
 '1',
 '4',
 '4',
 '2',
 '1',
 '4',
 '2',
 '1',
 '11',
 '0',
 '1',
 '8',
 '1',
 '2',
 '3',
 '2',
 '2',
 '4',
 '2',
 '1',
 '1',
 '15',
 '4',
 '3',
 '1',
 '1',
 '5',
 '2',
 '1',
 '5',
 '6',
 '0',
 '1',
 '8',
 '6',
 '4',
 '2',
 '10',
 '3',
 '15',
 '13',
 '3',
 '5',
 '12',
 '1',
 '2',
 '5',
 '6',
 '11',
 '3',
 '3',
 '3',
 '1',
 '5',
 '6',
 '7',
 '3',
 '9',
 '11',
 '3',
 '6',
 '3',
 '10',
 '2',
 '5',
 '7',
 '3',
 '3',
 '7',
 '7',
 '21',
 '3',
 '4',
 '7',
 '1',
 '2',
 '10',
 '5',
 '3',
 '4',
 '1',
 '3',
 '10',
 '21',
 '6',
 '2',
 '9',
 '8',
 '2',
 '4',
 '6',
 '3',
 '10',
 '4',
 '4',
 '1',
 '4',
 '10',
 '3',
 '8',
 '6',
 '1',
 '7',
 '8',
 '15',
 '5',
 '4',
 '12',
 '2',
 '3',
 '1',
 '1',
 '1',
 '6',
 '5',
 '5',
 '2',
 '6',
 '1',
 '2',
 '1',
 '5',
 '14',
 '3',
 '7',
 '11',
 '7',
 '3',
 '6',
 '9',
 '2',
 '5',
 '2',
 '1',
 '2',
 '3',
 '5',
 '3',
 '2',
 '6',
 '5',
 '3',
 '8',
 '2',
 '2',
 '16',
 '7',
 '4',
 '3',
 '8',
 '6',
 '9',
 '10',
 '6',
 '2',
 '11',
 '5',
 '15',
 '19',
 '2',
 '4',
 '6',
 '10',
 '5',
 '6',
 '7',
 '11',
 '6',
 '2',
 '8',
 '7',
 '11',
 '2',
 '2',
 '4',
 '2',
 '1',
 '10',
 '13',
 '6',
 '3',
 '6',
 '10',
 '20',
 '17',
 '4',
 '7',
 '3',
 '2',
 '12',
 '6',
 '1',
 '2',
 '5',
 '6',
 '8',
 '7',
 '4',
 '1',
 '6',
 '2',
 '7',
 '2',
 '3',
 '0',
 '2',
 '7',
 '8',
 '1',
 '1',
 '2',
 '6',
 '5',
 '4',
 '6',
 '1',
 '8',
 '4',
 '5',
 '9',
 '7',
 '4',
 '4',
 '5',
 '3',
 '8',
 '4',
 '4',
 '18',
 '5',
 '5',
 '4',
 '2',
 '3',
 '2',
 '1',
 '3',
 '15',
 '3',
 '5',
 '9',
 '2',
 '2',
 '13',
 '8',
 '5',
 '16',
 '2',
 '2',
 '6',
 '4',
 '3',
 '8',
 '2',
 '13',
 '4',
 '1',
 '5',
 '6',
 '2',
 '7',
 '4',
 '13',
 '7',
 '6',
 '8',
 '8',
 '4',
 '2',
 '8',
 '8',
 '9',
 '3',
 '10',
 '0',
 '0',
 '12',
 '2',
 '2',
 '5',
 '6',
 '9',
 '3',
 '6',
 '6',
 '17',
 '2',
 '3',
 '4',
 '3',
 '2',
 '4',
 '18',
 '1',
 '4',
 '4',
 '5',
 '10',
 '6',
 '5',
 '3',
 '6',
 '2',
 '10',
 '7',
 '7',
 '6',
 '7',
 '5',
 '3',
 '3',
 '1',
 '16',
 '2',
 '3',
 '8',
 '1',
 '5',
 '1',
 '7',
 '4',
 '2',
 '9',
 '11',
 '11',
 '2',
 '5',
 '13',
 '4',
 '4',
 '11',
 '9',
 '2',
 '10',
 '4',
 '5',
 ...]

In [59]:
with open('cs1_indices.txt') as f:
    cs1_lines = f.readlines()

In [60]:
cs1_lines = [item[:-1] for item in cs1_lines]
cs1_lines

['0',
 '0',
 '0',
 '7',
 '1',
 '2',
 '2',
 '2',
 '5',
 '9',
 '5',
 '9',
 '3',
 '4',
 '8',
 '3',
 '6',
 '2',
 '4',
 '1',
 '1',
 '4',
 '3',
 '0',
 '1',
 '3',
 '2',
 '0',
 '3',
 '6',
 '2',
 '9',
 '0',
 '9',
 '1',
 '2',
 '4',
 '7',
 '3',
 '0',
 '3',
 '6',
 '0',
 '2',
 '6',
 '5',
 '1',
 '7',
 '5',
 '6',
 '2',
 '3',
 '0',
 '2',
 '2',
 '14',
 '12',
 '5',
 '29',
 '8',
 '1',
 '0',
 '2',
 '0',
 '10',
 '5',
 '1',
 '8',
 '1',
 '9',
 '3',
 '5',
 '2',
 '0',
 '0',
 '4',
 '4',
 '2',
 '0',
 '2',
 '1',
 '0',
 '1',
 '2',
 '2',
 '4',
 '2',
 '0',
 '4',
 '1',
 '0',
 '5',
 '1',
 '3',
 '4',
 '0',
 '3',
 '2',
 '2',
 '3',
 '8',
 '8',
 '3',
 '0',
 '9',
 '10',
 '9',
 '1',
 '9',
 '1',
 '9',
 '2',
 '4',
 '4',
 '2',
 '9',
 '0',
 '0',
 '8',
 '11',
 '4',
 '18',
 '11',
 '2',
 '1',
 '5',
 '8',
 '5',
 '3',
 '5',
 '8',
 '2',
 '1',
 '1',
 '1',
 '2',
 '11',
 '0',
 '6',
 '5',
 '1',
 '5',
 '10',
 '3',
 '1',
 '4',
 '0',
 '0',
 '2',
 '11',
 '0',
 '1',
 '1',
 '0',
 '15',
 '0',
 '14',
 '6',
 '1',
 '1',
 '0',
 '2',
 '1',
 '2',
 '4',
 '0',
 '6',
 '7',
 '7',
 '8',
 '18',
 '0',
 '6',
 '5',
 '0',
 '12',
 '0',
 '11',
 '14',
 '0',
 '0',
 '2',
 '6',
 '3',
 '13',
 '2',
 '0',
 '2',
 '0',
 '17',
 '2',
 '5',
 '1',
 '14',
 '9',
 '0',
 '0',
 '11',
 '0',
 '2',
 '2',
 '4',
 '3',
 '5',
 '0',
 '2',
 '4',
 '1',
 '4',
 '4',
 '12',
 '4',
 '16',
 '8',
 '2',
 '8',
 '0',
 '2',
 '0',
 '11',
 '0',
 '5',
 '7',
 '2',
 '1',
 '7',
 '3',
 '8',
 '0',
 '0',
 '5',
 '2',
 '0',
 '9',
 '10',
 '4',
 '4',
 '12',
 '1',
 '3',
 '6',
 '0',
 '2',
 '17',
 '3',
 '5',
 '0',
 '1',
 '8',
 '2',
 '3',
 '5',
 '7',
 '3',
 '0',
 '0',
 '12',
 '2',
 '2',
 '12',
 '16',
 '3',
 '10',
 '1',
 '6',
 '0',
 '8',
 '4',
 '0',
 '8',
 '2',
 '4',
 '2',
 '3',
 '6',
 '6',
 '9',
 '2',
 '0',
 '0',
 '9',
 '12',
 '7',
 '0',
 '2',
 '6',
 '3',
 '0',
 '0',
 '0',
 '5',
 '3',
 '3',
 '4',
 '4',
 '1',
 '0',
 '7',
 '17',
 '6',
 '2',
 '13',
 '3',
 '3',
 '0',
 '2',
 '18',
 '0',
 '13',
 '5',
 '5',
 '1',
 '1',
 '0',
 '13',
 '5',
 '0',
 '2',
 '0',
 '3',
 '0',
 '8',
 '0',
 '5',
 '0',
 '2',
 '1',
 '0',
 '13',
 '5',
 '4',
 '6',
 '0',
 '21',
 '4',
 '7',
 '9',
 '1',
 '0',
 '13',
 '0',
 '16',
 '5',
 '11',
 '7',
 '0',
 '9',
 '4',
 '4',
 '2',
 '3',
 '0',
 '3',
 '3',
 '6',
 '0',
 '14',
 '11',
 '2',
 '0',
 '17',
 '9',
 '5',
 '2',
 '3',
 '11',
 '0',
 '4',
 '21',
 '14',
 '0',
 '1',
 '0',
 '4',
 '0',
 '3',
 '0',
 '10',
 '8',
 '3',
 '7',
 '3',
 '0',
 '3',
 '0',
 '0',
 '0',
 '1',
 '3',
 '2',
 '2',
 '6',
 '4',
 '5',
 '0',
 '14',
 '0',
 '0',
 '4',
 '1',
 '3',
 '3',
 '3',
 '6',
 '8',
 '10',
 '1',
 '2',
 '1',
 '2',
 '1',
 '14',
 '3',
 '5',
 '7',
 '2',
 '4',
 '3',
 '5',
 '4',
 '8',
 '5',
 '1',
 '3',
 '6',
 '1',
 '8',
 '0',
 '11',
 '0',
 '0',
 '13',
 '3',
 '13',
 '11',
 '3',
 '12',
 '2',
 '1',
 '7',
 '2',
 '12',
 '5',
 '0',
 '0',
 '6',
 '1',
 '4',
 '12',
 '0',
 '1',
 '2',
 '4',
 '1',
 '3',
 '5',
 '0',
 '21',
 '4',
 '6',
 '3',
 '3',
 '5',
 '9',
 '0',
 '10',
 '11',
 '5',
 '4',
 '4',
 '4',
 '3',
 '3',
 '2',
 '2',
 '2',
 '14',
 '6',
 '6',
 '4',
 '2',
 '1',
 '4',
 '2',
 '10',
 '2',
 '1',
 '1',
 '1',
 '3',
 '4',
 '5',
 '2',
 '3',
 '4',
 '3',
 '4',
 '11',
 '4',
 '0',
 '9',
 '5',
 '3',
 '7',
 '0',
 '4',
 '12',
 '1',
 '0',
 '2',
 '1',
 '5',
 '13',
 '6',
 '6',
 '3',
 '0',
 '0',
 '2',
 '2',
 '0',
 '2',
 '2',
 '0',
 '0',
 '2',
 '4',
 '6',
 '0',
 '20',
 '5',
 '0',
 '10',
 '7',
 '4',
 '5',
 '0',
 '5',
 '5',
 '4',
 '1',
 '1',
 '6',
 '4',
 '0',
 '0',
 '12',
 '0',
 '8',
 '5',
 '13',
 '4',
 '3',
 '7',
 '5',
 '0',
 '5',
 '12',
 '0',
 '1',
 '0',
 '1',
 '1',
 '8',
 '0',
 '5',
 '2',
 '4',
 '7',
 '11',
 '0',
 '3',
 '3',
 '3',
 '4',
 '5',
 '2',
 '12',
 '1',
 '4',
 '7',
 '4',
 '3',
 '0',
 '3',
 '0',
 '2',
 '6',
 '2',
 '0',
 '6',
 '4',
 '3',
 '3',
 '5',
 '2',
 '3',
 '5',
 '3',
 '6',
 '3',
 '11',
 '2',
 '0',
 '4',
 '1',
 '6',
 '4',
 '1',
 '1',
 '21',
 '10',
 '5',
 '6',
 '3',
 '12',
 '6',
 '5',
 '0',
 '5',
 '0',
 '2',
 '3',
 '3',
 '1',
 '3',
 '0',
 '8',
 '3',
 '1',
 '0',
 '3',
 '0',
 '0',
 '2',
 '8',
 '0',
 '1',
 '11',
 '7',
 '5',
 '6',
 '4',
 '9',
 '2',
 '5',
 '2',
 '3',
 '6',
 '5',
 '8',
 '19',
 '2',
 '0',
 '3',
 '2',
 '1',
 '0',
 '2',
 '7',
 '5',
 '7',
 '16',
 '5',
 '10',
 '0',
 '0',
 '3',
 '9',
 '3',
 '2',
 '13',
 '5',
 '1',
 '2',
 '5',
 '5',
 '8',
 '2',
 '0',
 '5',
 '8',
 '2',
 '1',
 '0',
 '15',
 '2',
 '8',
 '1',
 '8',
 '3',
 '5',
 '1',
 '1',
 '6',
 '13',
 '6',
 '5',
 '1',
 '2',
 '0',
 '1',
 '11',
 '0',
 '8',
 '13',
 '6',
 '1',
 '1',
 '6',
 '0',
 '0',
 '3',
 '2',
 '3',
 '7',
 '11',
 '1',
 '3',
 '9',
 '2',
 '5',
 '11',
 '7',
 '2',
 '1',
 '18',
 '2',
 '8',
 '3',
 '3',
 '4',
 '0',
 '1',
 '4',
 '0',
 '0',
 '7',
 '0',
 '6',
 '3',
 '2',
 '0',
 '9',
 '3',
 '0',
 '2',
 '13',
 '0',
 '25',
 '14',
 '9',
 '6',
 '2',
 '8',
 '4',
 '5',
 '4',
 '2',
 '0',
 '0',
 '2',
 '0',
 '5',
 '3',
 '6',
 '4',
 '0',
 '1',
 '7',
 '2',
 '1',
 '1',
 '3',
 '0',
 '2',
 '1',
 '1',
 '17',
 '2',
 '3',
 '0',
 '8',
 '3',
 '1',
 '0',
 '5',
 '5',
 '0',
 '7',
 '3',
 '9',
 '0',
 '7',
 '0',
 '4',
 '2',
 '2',
 '20',
 '8',
 '5',
 '2',
 '5',
 '8',
 '0',
 '0',
 '6',
 '6',
 '2',
 '6',
 '9',
 '14',
 '1',
 '4',
 '1',
 '1',
 '9',
 '6',
 '9',
 '0',
 '2',
 '0',
 '0',
 '3',
 '0',
 '1',
 '5',
 '1',
 '6',
 '3',
 '5',
 '2',
 '8',
 '8',
 '13',
 '6',
 '6',
 '12',
 '2',
 '0',
 '2',
 '7',
 '2',
 '2',
 '5',
 '3',
 '9',
 '1',
 '0',
 '2',
 '14',
 '8',
 '7',
 '8',
 '4',
 '0',
 '4',
 '4',
 '5',
 '4',
 '7',
 '1',
 '4',
 '4',
 '4',
 '9',
 '21',
 '1',
 '3',
 '6',
 '2',
 '5',
 '3',
 '7',
 '0',
 '2',
 '3',
 '11',
 '17',
 '0',
 '9',
 '1',
 '4',
 '0',
 '9',
 '5',
 '0',
 '1',
 '0',
 '5',
 '0',
 '1',
 '7',
 '3',
 '2',
 '1',
 '0',
 '0',
 '13',
 '2',
 '4',
 '2',
 '1',
 '0',
 '0',
 '4',
 '5',
 '1',
 '11',
 '0',
 '0',
 '4',
 '5',
 '5',
 '14',
 '2',
 '2',
 '1',
 '0',
 '4',
 '9',
 '4',
 '2',
 '0',
 '8',
 '10',
 '4',
 '9',
 '12',
 '11',
 '2',
 '3',
 '14',
 '0',
 '1',
 '3',
 '7',
 '4',
 '9',
 '0',
 '2',
 '4',
 '2',
 '6',
 '0',
 '2',
 '4',
 '0',
 '6',
 '1',
 '8',
 '9',
 '2',
 '11',
 '2',
 '8',
 '0',
 '4',
 '2',
 '4',
 '6',
 '8',
 '0',
 '10',
 '5',
 '5',
 '19',
 '1',
 '16',
 '10',
 '0',
 '0',
 '5',
 '8',
 '3',
 '0',
 '6',
 '2',
 '4',
 '2',
 '3',
 '14',
 '2',
 '8',
 '19',
 '1',
 '6',
 '3',
 '5',
 '8',
 '6',
 '1',
 '2',
 '3',
 '2',
 '9',
 '3',
 '3',
 '0',
 '3',
 ...]

In [61]:
df = df[['original_sentence', 'zh_word_index', 'cs_back_word']]
df['cs1_index'] = cs1_lines
df.head()

,original_sentence,zh_word_index,cs_back_word,cs1_index
0,rich neighborhood ， 非常 安全 （ 这里 属于 富人 区 ） ， 旁边 ...,0,非常,0
1,lease 从 八月 开始 ， 具体 日期 可以 商量 。,0,从,0
2,house 一共 有 两 层 + 地下室 。,0,一共,0
3,一共 有 两 个 可以 洗澡 的 bathroom 。,7,NaN,7
4,整个 house 家具 齐全 。,1,家具,1

In [62]:
df = df[['cs1_index', 'cs_back_word', 'original_sentence']]

In [63]:
len(df)

1476

In [64]:
df = df.dropna()
len(df)

1128

In [65]:
df['cs2_index'] = cs2_lines
df.head()

,cs1_index,cs_back_word,original_sentence,cs2_index
0,0,非常,rich neighborhood ， 非常 安全 （ 这里 属于 富人 区 ） ， 旁边 ...,3
1,0,从,lease 从 八月 开始 ， 具体 日期 可以 商量 。,1
2,0,一共,house 一共 有 两 层 + 地下室 。,1
4,1,家具,整个 house 家具 齐全 。,2
6,2,和,空调 有 window ac 和 暖气 。,5

In [66]:
df['distance'] = df.apply(lambda row: int(row.cs2_index) - int(row.cs1_index), axis=1)
df.head()

,cs1_index,cs_back_word,original_sentence,cs2_index,distance
0,0,非常,rich neighborhood ， 非常 安全 （ 这里 属于 富人 区 ） ， 旁边 ...,3,3
1,0,从,lease 从 八月 开始 ， 具体 日期 可以 商量 。,1,1
2,0,一共,house 一共 有 两 层 + 地下室 。,1,1
4,1,家具,整个 house 家具 齐全 。,2,1
6,2,和,空调 有 window ac 和 暖气 。,5,3

In [67]:
df = df[['original_sentence', 'cs1_index', 'cs2_index', 'distance']]
df.head()

,original_sentence,cs1_index,cs2_index,distance
0,rich neighborhood ， 非常 安全 （ 这里 属于 富人 区 ） ， 旁边 ...,0,3,3
1,lease 从 八月 开始 ， 具体 日期 可以 商量 。,0,1,1
2,house 一共 有 两 层 + 地下室 。,0,1,1
4,整个 house 家具 齐全 。,1,2,1
6,空调 有 window ac 和 暖气 。,2,5,3

In [68]:
df.to_csv('cs2-cs1 distances.csv')

In [91]:
df = pd.read_csv('cs2-cs1 distances.csv')
df.head()

,Unnamed: 0,original_sentence,cs1_index,cs2_index,distance
0,0,rich neighborhood ， 非常 安全 （ 这里 属于 富人 区 ） ， 旁边 ...,0,3,3
1,1,lease 从 八月 开始 ， 具体 日期 可以 商量 。,0,1,1
2,2,house 一共 有 两 层 + 地下室 。,0,1,1
3,4,整个 house 家具 齐全 。,1,2,1
4,6,空调 有 window ac 和 暖气 。,2,5,3

In [92]:
distances = df['distance']
np.min(distances)

1

In [98]:
np.quantile(distances, 0.25)

1.0

In [99]:
np.median(distances)

2.0

In [100]:
np.mean(distances)

2.100177304964539

In [101]:
np.quantile(distances, 0.75)

2.0

In [102]:
np.max(distances)

14