In [1]:
import pandas as pd

In [2]:
#df = pd.read_csv("data/get_experiment_sentences/input/11152019/11152019_two_entropies_appended_input_R_v4.csv")
#df.head()
df = pd.read_csv("redoing_cs_data.csv")
df.head()

,sent_type,university,sent_id,aligned_to,original_sentence,eng_translation,zh_translation,cs_word_id,first_cs_word_form,first_cs_word_translation,...,surprisal_values,average_surprisal,bilingual_corpus_frequency_negative_log_first_cs_word,bilingual_corpus_frequency_negative_log_first_cs_word_trans,length_first_cs_word_form,length_first_cs_word_trans,dependency_distance,if_it_is_root,if_previous_word_is_punctuation,surprisal_of_previous_word
0,code-switch,CMU,2,CMU_296,rich neighborhood ， 非常 安全 （ 这里 属于 富人 区 ） ， 旁边 ...,Rich neighborhood is very safe (it belongs to ...,富人 区 ， 非常 安全 （ 这里 属于 富人 区 ） ， 旁边 就 是 公园 ， 附近 还...,1,rich,富人,...,6.100998 1.320391 0.7630151 4.4722 3.20577 2.7...,3.144718,11.319098,10.402807,4,2,1,0,NaN,NaN
1,code-switch,CMU,4,CMU_3006,lease 从 八月 开始 ， 具体 日期 可以 商量 。,Lease will begin in August and the date is neg...,租约 从 八月 开始 ， 具体 日期 可以 商量 。,1,lease,租约,...,6.527233 3.646975 4.193077 1.173965 0.5694761 ...,3.155464,7.348806,10.066335,5,2,8,0,NaN,NaN
2,code-switch,CMU,5,CMU_70,house 一共 有 两 层 + 地下室 。,House has two floors plus basement.,房子 一共 有 两 层 + 地下室 。,1,house,房子,...,5.512905 5.228868 0.5955775 1.38895 2.136289 4...,3.268832,6.694125,7.084991,5,2,2,0,NaN,NaN
3,code-switch,CMU,6,CMU_6777,一共 有 两 个 可以 洗澡 的 bathroom 。,There are two bathroom for bathing.,一共 有 两 个 可以 洗澡 的 浴室 。,8,bathroom,浴室,...,4.509301 0.2903937 1.38895 0.4321387 3.465795 ...,2.642274,8.611048,9.709660,8,2,6,0,0.0,0.895995
4,code-switch,CMU,9,CMU_4373,整个 house 家具 齐全 。,The whole house is fully furnished.,整个 房子 家具 齐全 。,2,house,房子,...,3.732348 4.488641 5.760885 6.166569 0.8237057,4.194430,6.694125,7.084991,5,2,1,0,0.0,3.732348

In [3]:
df.head(1)

,sent_type,university,sent_id,aligned_to,original_sentence,eng_translation,zh_translation,cs_word_id,first_cs_word_form,first_cs_word_translation,...,surprisal_values,average_surprisal,bilingual_corpus_frequency_negative_log_first_cs_word,bilingual_corpus_frequency_negative_log_first_cs_word_trans,length_first_cs_word_form,length_first_cs_word_trans,dependency_distance,if_it_is_root,if_previous_word_is_punctuation,surprisal_of_previous_word
0,code-switch,CMU,2,CMU_296,rich neighborhood ， 非常 安全 （ 这里 属于 富人 区 ） ， 旁边 ...,Rich neighborhood is very safe (it belongs to ...,富人 区 ， 非常 安全 （ 这里 属于 富人 区 ） ， 旁边 就 是 公园 ， 附近 还...,1,rich,富人,...,6.100998 1.320391 0.7630151 4.4722 3.20577 2.7...,3.144718,11.319098,10.402807,4,2,1,0,NaN,NaN

In [5]:
df.head(1)['zh_translation']

0    富人 区 ， 非常 安全 （ 这里 属于 富人 区 ） ， 旁边 就 是 公园 ， 附近 还...
Name: zh_translation, dtype: object

In [7]:
draft = list(list(df.head(1)['zh_translation'])[0].split())

In [8]:
#punct = ['，', '）', '（', '。']

In [9]:
#no_punct = [x for x in draft if x not in punct]

In [10]:
#no_punct

In [11]:
row = df[10:11]

In [12]:
row

,sent_type,university,sent_id,aligned_to,original_sentence,eng_translation,zh_translation,cs_word_id,first_cs_word_form,first_cs_word_translation,...,surprisal_values,average_surprisal,bilingual_corpus_frequency_negative_log_first_cs_word,bilingual_corpus_frequency_negative_log_first_cs_word_trans,length_first_cs_word_form,length_first_cs_word_trans,dependency_distance,if_it_is_root,if_previous_word_is_punctuation,surprisal_of_previous_word
10,code-switch,CMU,17,CMU_3964,有 兴趣 者 ， 请 email 短信 介绍 一下 自己 情况 。,"Interested, please email SMS to introduce your...",有 兴趣 者 ， 请 发送 短信 介绍 一下 自己 情况 。,6,email,发送,...,2.715695 4.139023 3.022636 0.6238034 3.313639 ...,3.005617,7.630219,10.220486,5,2,0,1,0.0,3.313639

In [13]:
list(list(row['zh_translation'])[0].split())

['有', '兴趣', '者', '，', '请', '发送', '短信', '介绍', '一下', '自己', '情况', '。']

In [14]:
df.head(1)

,sent_type,university,sent_id,aligned_to,original_sentence,eng_translation,zh_translation,cs_word_id,first_cs_word_form,first_cs_word_translation,...,surprisal_values,average_surprisal,bilingual_corpus_frequency_negative_log_first_cs_word,bilingual_corpus_frequency_negative_log_first_cs_word_trans,length_first_cs_word_form,length_first_cs_word_trans,dependency_distance,if_it_is_root,if_previous_word_is_punctuation,surprisal_of_previous_word
0,code-switch,CMU,2,CMU_296,rich neighborhood ， 非常 安全 （ 这里 属于 富人 区 ） ， 旁边 ...,Rich neighborhood is very safe (it belongs to ...,富人 区 ， 非常 安全 （ 这里 属于 富人 区 ） ， 旁边 就 是 公园 ， 附近 还...,1,rich,富人,...,6.100998 1.320391 0.7630151 4.4722 3.20577 2.7...,3.144718,11.319098,10.402807,4,2,1,0,NaN,NaN

In [16]:
new_df = pd.DataFrame(columns = ['university', 'sent_id', 'original_sentence', 'translation', 'word_id', 'first_cs_word_form', 'first_cs_word_translation', 'governer_first_cs_word', 'preceding_word'])

In [17]:
new_df

Empty DataFrame
Columns: [sent_type, university, sent_id, aligned_to, original_sentence, eng_translation, zh_translation, cs_word_id, first_cs_word_form, first_cs_word_translation, Unnamed: 10, Unnamed: 11, Unnamed: 12, Unnamed: 13, frequency_negative_ln_first_cs_word_trans, surprisal_first_cs_word_trans, pos_tag_first_cs_word_trans, governor_first_cs_word_trans, deprel_first_cs_word_trans, surprisal_values, average_surprisal, bilingual_corpus_frequency_negative_log_first_cs_word, bilingual_corpus_frequency_negative_log_first_cs_word_trans, length_first_cs_word_form, length_first_cs_word_trans, dependency_distance, if_it_is_root, if_previous_word_is_punctuation, surprisal_of_previous_word]
Index: []

[0 rows x 29 columns]

In [21]:
prec = []

for index, row in df.iterrows():
    if row['sent_type'] == 'code-switch':
        og_list_of_words = list(list(df[index:index+1]['original_sentence'])[0].split())
        chinese_list_of_words = list(list(df[index:index+1]['zh_translation'])[0].split())
        #print(og_list_of_words)
        #print()
        #print(chinese_list_of_words)
        #print(row['sent_id'])
        try:
        
            if row['cs_word_id'] == 1:
                prec.append('</s>')
    
            else: #word_id!=1 and it is a root 
                prec.append(og_list_of_words[row['cs_word_id']-2])
                
        except: 
            pass

In [14]:
gov = []

for index, row in df.iterrows():
    og_list_of_words = list(list(df[index:index+1]['original_sentence'])[0].split())
    #print(og_list_of_words)
    if row['if_it_is_root'] == 1:
        try:
            word_index = row["cs_word_id"]
            #print(word_index)
            word = og_list_of_words[word_index-1]
        except:
            word = 'NaN'
    else:
        try:
            word_index = row["governor_first_cs_word_trans"]
            word = og_list_of_words[word_index-1]
            #print(word_index)
        except:
            word = 'NaN'
    gov.append(word)

In [16]:
print(gov.count('NaN'))

21

In [17]:
textfile = open("redone_cs_governor_words.txt", "w")
for element in gov:
    textfile.write(element + "\n")
textfile.close()

In [22]:
textfile = open("redone_cs_preceding_words.txt", "w")
for element in prec:
    textfile.write(element + "\n")
textfile.close()

In [110]:
for index, row in df.iterrows():
    if row['sent_type'] == 'code-switch':
        og_list_of_words = list(list(df[index:index+1]['original_sentence'])[0].split())
        chinese_list_of_words = list(list(df[index:index+1]['zh_translation'])[0].split())
        #print(og_list_of_words)
        #print()
        #print(chinese_list_of_words)
        #print(row['sent_id'])
        try:
        
            if row['word_id'] == 1 and row['if_it_is_root'] == 0:

                new_df = new_df.append({'university': row['university'], 'sent_id': row['sent_id'], 
                                   'original_sentence': row['original_sentence'], 'translation': row['translation'],
                                   'word_id': row['word_id'], 'first_cs_word_form': row['first_cs_word_form'],
                                   'first_cs_word_translation': row['first_cs_word_translation'],
                                   'governer_first_cs_word': og_list_of_words[row['governor_first_cs_word_trans']-1], 
                                        'preceding_word': 'none' }, ignore_index=True)

            elif row['word_id'] == 1 and row['if_it_is_root'] == 1:
                new_df = new_df.append({'university': row['university'], 'sent_id': row['sent_id'], 
                                   'original_sentence': row['original_sentence'], 'translation': row['translation'],
                                   'word_id': row['word_id'], 'first_cs_word_form': row['first_cs_word_form'],
                                   'first_cs_word_translation': row['first_cs_word_translation'],
                                   'governer_first_cs_word': row['first_cs_row_translation'], 
                                        'preceding_word': 'none' }, ignore_index=True)

            elif row['word_id'] != 1 and row['if_it_is_root'] == 0:
                new_df = new_df.append({'university': row['university'], 'sent_id': row['sent_id'], 
                                   'original_sentence': row['original_sentence'], 'translation': row['translation'],
                                   'word_id': row['word_id'], 'first_cs_word_form': row['first_cs_word_form'],
                                   'first_cs_word_translation': row['first_cs_word_translation'],
                                   'governer_first_cs_word': og_list_of_words[row['governor_first_cs_word_trans']-1], 
                                        'preceding_word': og_list_of_words[row['word_id']-2] }, ignore_index=True)

            else: #word_id!=1 and it is a root 
                new_df = new_df.append({'university': row['university'], 'sent_id': row['sent_id'], 
                                   'original_sentence': row['original_sentence'], 'translation': row['translation'],
                                   'word_id': row['word_id'], 'first_cs_word_form': row['first_cs_word_form'],
                                   'first_cs_word_translation': row['first_cs_word_translation'],
                                   'governer_first_cs_word': row['first_cs_word_translation'], 
                                        'preceding_word': og_list_of_words[row['word_id']-2] }, ignore_index=True)
        except: 
            pass

In [111]:
new_df

,university,sent_id,original_sentence,translation,word_id,first_cs_word_form,first_cs_word_translation,governer_first_cs_word,preceding_word
0,CMU,2,rich neighborhood ， 非常 安全 （ 这里 属于 富人 区 ） ， 旁边 ...,富人 区 ， 非常 安全 （ 这里 属于 富人 区 ） ， 旁边 就 是 公园 ， 附近 还...,1,rich,富人,neighborhood,none
1,CMU,4,lease 从 八月 开始 ， 具体 日期 可以 商量 。,租约 从 八月 开始 ， 具体 日期 可以 商量 。,1,lease,租约,商量,none
2,CMU,5,house 一共 有 两 层 + 地下室 。,房子 一共 有 两 层 + 地下室 。,1,house,房子,有,none
3,CMU,6,一共 有 两 个 可以 洗澡 的 bathroom 。,一共 有 两 个 可以 洗澡 的 浴室 。,8,bathroom,浴室,有,的
4,CMU,9,整个 house 家具 齐全 。,整个 房子 家具 齐全 。,2,house,房子,家具,整个
...,...,...,...,...,...,...,...,...,...
1416,PIT,940,然后 就 可以 email 群发 附近 的 dealer 要求 报价 ， 然后 让 他们 互...,然后 就 可以 电子 邮件 群发 附近 的 卖家 要求 报价 ， 然后 让 他们 互相 竞价 。,4,email,电子,群发,可以
1417,PIT,946,toilet 厕所 excuse me .,厕所 对不起 ， 请 问 厕所 在 哪儿 。,2,toilet,对不起,对不起,toilet
1418,PIT,951,行李 传送带 luggage claim ;,行李 传送带 行李 带 ；,3,luggage,行李,claim,传送带
1419,PIT,952,baggage claim 国际 出港 international departure,行李 带 国际 出港 国际 出发,1,baggage,行李,claim,none
1420,PIT,964,downtown 有 个 公寓 叫 washington plaza ， view 啊 户型...,市区 有 个 公寓 叫 华盛顿 广场 ， 风景 啊 户型 啊 ， 都 极 好 ， 没有 车 ...,1,downtown,市区,有,none

In [112]:
new_df.to_csv('governer_and_preceding_words_extracted.csv')

In [116]:
print(new_df.shape[0])

1421

In [118]:
new_df[70:75]

,university,sent_id,original_sentence,translation,word_id,first_cs_word_form,first_cs_word_translation,governer_first_cs_word,preceding_word
70,CMU,170,main office 就 在 地下 一 楼 ， 咨询 非常 方便 。,总 办公室 就 在 地下 一 楼 ， 咨询 非常 方便 。,1,main,总,office,none
71,CMU,171,我 希望 租 一 个 房间 前 一 整 年 lease 。,我 希望 租 一 个 房间 前 一 整 年 的 租期 。,11,lease,的,前,年
72,CMU,177,全新 的 宜家 买 的 twin size 的 床 和 书桌 柜子 ， 房间 内 有 clo...,全新 的 宜家 买 的 小 单人床 的 床 和 书桌 柜子 ， 房间 内 有 衣柜 。,6,twin,小,size,的
73,CMU,178,pn-3 call 或者 text 都 阔 以 。,pn-3 打 电话 或者 发 短信 都 阔 以 。,2,call,打,打,pn-3
74,CMU,180,我俩 都 是 刚 毕业 没 多久 的 young professional ， 安静 好 相...,我俩 都 是 刚 毕业 没 多久 的 年轻 职员 ， 安静 好 相处 ， 会 居家 也 爱 ...,9,young,年轻,professional,的

In [98]:
row_check = df.loc[df['sent_id'] == 16]

In [99]:
row_check

,sent_type,university,sent_id,aligned_to,original_sentence,translation,word_id,first_cs_word_form,first_cs_word_translation,frequency_negative_ln_first_cs_word_trans,...,if_it_is_root,if_previous_word_is_punctuation,surprisal_of_previous_word,25_50_25_percent_location,10_80_10_percent_location,30_40_30_percent_location,first_middle_last_location,translation_sentence_length,entropy_at_cs_point,entropy_one_word_after_cs_point
18,code-switch,CMU,16,CMU_64,二 楼 是 三 间 卧室 和 一 个 full 卫生间 。,二 楼 是 三 间 卧室 和 一 个 设施 完全 的 卫生间 。,10,full,设施,35.963124,...,0,0.0,5.729619,2,2,3,2,14,2.49488,1.60513

In [109]:
list(row_check['original_sentence'])[0].split()

['二', '楼', '是', '三', '间', '卧室', '和', '一', '个', 'full', '卫生间', '。']