In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('11152019_appended_input_R_v4_new_15_11_2019.csv')

In [4]:
df.head()

,sent_type,university,sent_id,aligned_to,original_sentence,translation,word_id,first_cs_word_form,first_cs_word_translation,frequency_negative_ln_first_cs_word_trans,...,surprisal_values,average_surprisal,bilingual_corpus_frequency_negative_log_first_cs_word,bilingual_corpus_frequency_negative_log_first_cs_word_trans,length_first_cs_word_form,length_first_cs_word_trans,dependency_distance,if_it_is_root,if_previous_word_is_punctuation,surprisal_of_previous_word
0,code-switch,CMU,2,CMU_296,rich neighborhood ， 非常 安全 （ 这里 属于 富人 区 ） ， 旁边 ...,富人 区 ， 非常 安全 （ 这里 属于 富人 区 ） ， 旁边 就 是 公园 ， 附近 还...,1,rich,富人,46.615353,...,6.100998 1.320391 0.7630151 4.4722 3.20577 2.7...,3.144718,11.319098,10.402807,4.0,2,1,0,NaN,NaN
1,non-code-switch,CMU,296,CMU_2,,路上 一般 见到 都 是 学生 ， 很少 见到 游民 ， 公寓 对面 是 公园 和 一 个 ...,12,NaN,公寓,39.049880,...,5.688997 4.083399 5.282374 4.241812 0.7527016 ...,3.455918,NaN,7.358285,NaN,2,1,0,1.0,6.571874
2,code-switch,CMU,4,CMU_3006,lease 从 八月 开始 ， 具体 日期 可以 商量 。,租约 从 八月 开始 ， 具体 日期 可以 商量 。,1,lease,租约,41.578729,...,6.527233 3.646975 4.193077 1.173965 0.5694761 ...,3.155464,7.348806,10.066335,5.0,2,8,0,NaN,NaN
3,non-code-switch,CMU,3006,CMU_4,,房子 的 照片 在 附件 中 ， 还有 好多 照片 放 不 上来 啦 。,3,NaN,照片,37.173947,...,5.512905 1.253929 3.542832 1.976808 5.474577 0...,3.283953,NaN,8.754149,NaN,2,8,0,0.0,1.253929
4,code-switch,CMU,5,CMU_70,house 一共 有 两 层 + 地下室 。,房子 一共 有 两 层 + 地下室 。,1,house,房子,37.403903,...,5.512905 5.228868 0.5955775 1.38895 2.136289 4...,3.268832,6.694125,7.084991,5.0,2,2,0,NaN,NaN

In [6]:
non_cs = df.loc[df['sent_type'] == 'non-code-switch']

In [7]:
non_cs.head()

,sent_type,university,sent_id,aligned_to,original_sentence,translation,word_id,first_cs_word_form,first_cs_word_translation,frequency_negative_ln_first_cs_word_trans,...,surprisal_values,average_surprisal,bilingual_corpus_frequency_negative_log_first_cs_word,bilingual_corpus_frequency_negative_log_first_cs_word_trans,length_first_cs_word_form,length_first_cs_word_trans,dependency_distance,if_it_is_root,if_previous_word_is_punctuation,surprisal_of_previous_word
1,non-code-switch,CMU,296,CMU_2,,路上 一般 见到 都 是 学生 ， 很少 见到 游民 ， 公寓 对面 是 公园 和 一 个 ...,12,NaN,公寓,39.049880,...,5.688997 4.083399 5.282374 4.241812 0.7527016 ...,3.455918,NaN,7.358285,NaN,2,1,0,1.0,6.571874
3,non-code-switch,CMU,3006,CMU_4,,房子 的 照片 在 附件 中 ， 还有 好多 照片 放 不 上来 啦 。,3,NaN,照片,37.173947,...,5.512905 1.253929 3.542832 1.976808 5.474577 0...,3.283953,NaN,8.754149,NaN,2,8,0,0.0,1.253929
5,non-code-switch,CMU,70,CMU_5,,房子 共 有 三 个 厕所 。,1,NaN,房子,37.403903,...,5.512905 4.35849 3.044444 2.11923 0.4863122 4....,3.048914,NaN,7.084991,NaN,2,2,0,NaN,NaN
7,non-code-switch,CMU,6777,CMU_6,,没有 找到 寄存 的 地方 。,5,NaN,地方,34.498460,...,3.923701 2.707315 6.636431 1.30103 2.670942 0....,2.983802,NaN,8.716408,NaN,2,3,0,0.0,1.301030
9,non-code-switch,CMU,4373,CMU_9,,全部 木头 地板 ， 干净 。,2,NaN,木头,40.617086,...,4.274023 6.139354 2.307971 1.241405 5.898223 1...,3.490901,NaN,11.319098,NaN,2,1,0,0.0,4.274023

In [9]:
non_cs.to_csv('non_cs_sentences.csv')