In [21]:
import pandas as pd

In [22]:
df = pd.read_csv('redoing_cs_data.csv')
df.head()

,sent_type,university,sent_id,aligned_to,original_sentence,eng_translation,zh_translation,cs_word_id,first_cs_word_form,first_cs_word_translation,...,surprisal_values,average_surprisal,bilingual_corpus_frequency_negative_log_first_cs_word,bilingual_corpus_frequency_negative_log_first_cs_word_trans,length_first_cs_word_form,dependency_distance,if_it_is_root,if_previous_word_is_punctuation,surprisal_of_previous_word,surprisal_first_cs_word_trans
0,code-switch,CMU,2,CMU_296,rich neighborhood ， 非常 安全 （ 这里 属于 富人 区 ） ， 旁边 ...,Rich neighborhood is very safe (it belongs to ...,富人 区 ， 非常 安全 （ 这里 属于 富人 区 ） ， 旁边 就 是 公园 ， 附近 还...,1,rich,富人,...,6.100998 1.320391 0.7630151 4.4722 3.20577 2.7...,3.144718,11.319098,10.402807,4,1,0,NaN,NaN,6.100998
1,code-switch,CMU,4,CMU_3006,lease 从 八月 开始 ， 具体 日期 可以 商量 。,Lease will begin in August and the date is neg...,租约 从 八月 开始 ， 具体 日期 可以 商量 。,1,lease,租约,...,6.527233 3.646975 4.193077 1.173965 0.5694761 ...,3.155464,7.348806,10.066335,5,8,0,NaN,NaN,6.527233
2,code-switch,CMU,5,CMU_70,house 一共 有 两 层 + 地下室 。,House has two floors plus basement.,房子 一共 有 两 层 + 地下室 。,1,house,房子,...,5.512905 5.228868 0.5955775 1.38895 2.136289 4...,3.268832,6.694125,7.084991,5,2,0,NaN,NaN,5.512905
3,code-switch,CMU,6,CMU_6777,一共 有 两 个 可以 洗澡 的 bathroom 。,There are two bathrooms for bathing.,一共 有 两 个 可以 洗澡 的 浴室 。,8,bathroom,浴室,...,4.509301 0.2903937 1.38895 0.4321387 3.465795 ...,2.642274,8.611048,9.709660,8,6,0,0.0,0.895995,5.210801
4,code-switch,CMU,9,CMU_4373,整个 house 家具 齐全 。,The whole house is fully furnished.,整个 房子 家具 齐全 。,2,house,房子,...,3.732348 4.488641 5.760885 6.166569 0.8237057,4.194430,6.694125,7.084991,5,1,0,0.0,3.732348,4.488641

In [23]:
sents = df[['zh_translation', 'eng_translation', 'first_cs_word_form']]

In [24]:
sents.head()

,zh_translation,eng_translation,first_cs_word_form
0,富人 区 ， 非常 安全 （ 这里 属于 富人 区 ） ， 旁边 就 是 公园 ， 附近 还...,Rich neighborhood is very safe (it belongs to ...,rich
1,租约 从 八月 开始 ， 具体 日期 可以 商量 。,Lease will begin in August and the date is neg...,lease
2,房子 一共 有 两 层 + 地下室 。,House has two floors plus basement.,house
3,一共 有 两 个 可以 洗澡 的 浴室 。,There are two bathrooms for bathing.,bathroom
4,整个 房子 家具 齐全 。,The whole house is fully furnished.,house

In [25]:
pairs = []
for index, row in sents.iterrows():
    tup = (row['zh_translation'], row['eng_translation'], row['first_cs_word_form'])
    pairs.append(tup)

In [26]:
import random

In [27]:
rand = random.choices(pairs, k=148)

In [28]:
zh_translation = [pair[0] for pair in rand]
eng_translation = [pair[1] for pair in rand]
cs_word = [pair[2] for pair in rand]

In [29]:
final = pd.DataFrame(list(zip(zh_translation, eng_translation, cs_word)),
               columns =['zh_translation', 'eng_translation', 'first_cs_word_form'])
final

,zh_translation,eng_translation,first_cs_word_form
0,但是 在 邮件 里面 他 想 索要 我 的 地址 ， 想要 给 我 寄 支票 。,But in the email he wanted my address and he w...,email
1,欢迎 联系 并 告知 租房 要求 （ 简单 自我 介绍 ， 告知 入住 时间 ， 人数 ， ...,You are welcome to contact us and tell us the ...,or
2,一 间 中等 的 卧室 。,A medium bedroom.,bedroom
3,房子 有 中央 空调 循环 ， 通风 和 湿度 都 没有 没 问题 。,The house has central air-conditioning circula...,house
4,独 栋 住宅 中 的 一 个 最大 房间 ， 租金 为 ： 399$ / 月 。,"The largest room in the house, rent: $399 / mo...",house
...,...,...,...
143,如有 意向 ， 请 邮箱 联系 ： em@49,"If interested, please email: em@49",email
144,公寓 里 的 每 一 个 住户 她 几乎 都 认识 ， 是 一 位 非常 平易近人 的 女性 ！,She knows almost every one of the residents in...,a
145,小区 环境 非常 好 ， 安静 无 派对 ， 隔壁 邻居 是 老 先生 和 太太 。,"The neighborhood environment is very nice, qui...",party
146,公寓 有 免费 体育场 和 停车 坪 。,The apartment has a free gym and parking.,gym
147,目前 只有 两 个 房间 可 租 。,"Currently, only two rooms are available.",available

In [30]:
final.to_csv('for_precision_checking.csv')